### ISSUE TITLE
Parcellite hangs

### ISSUE THREAD

**Issue by Hultan** [ZaWertun/parcellite#2]
I hope this is the correct Github-page for this. On Manjaro/Cinnamon:

1. Open preferences by right clicking icon and select preferences.
2. Now click on the icon again, left-click I think, but try both a couple of times.
3. Now the application hangs.

When running from a terminal to reproduce the problem I could reproduce the problem and I got a lot of errors in the terminal:

`
(parcellite:16084): Gtk-CRITICAL **: 16:39:34.377: IA__gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed`

**Comment by ZaWertun** [comment]
Try commit 5b3a268aed5e2c6c48a94bf4bc36a08a1ea1b590.

**Comment by Hultan** [comment]
I think I managed to compile it and install it using the instructions on the main page, but I still get the error, even after a restart of the computer. If I look at the file in /usr/bin it has todays date and time so it looks like I have managed to compile it and install it correctly, but this is the first time I compile a program by myself so I might have messed up somehow...

**Comment by Hultan** [comment]
Hang on, when I type 

`git clone https://github.com/ZaWertun/parcellite.git`

do I actually get the commit that you referred to? Very new to Git/Github as well...

[Edit:] Confirmed, I can see your changes in main.c...

**Comment by ZaWertun** [comment]
You don't need to install version with fix, just run compiled binary from the `build` dir (`cd build; ./parcellite`).
Just don't forget to close version installed with package manager.

**Comment by Hultan** [comment]
Nope, sorry, still doesn't work, even if I run from the build directory. And thanks for letting me know about not needing to install. I am learning a lot today, almost a complete c/c++ developer now :-)

**Comment by ZaWertun** [comment]
Function `gtk_dialog_run` blocks all gui: https://github.com/ZaWertun/parcellite/blob/abd0a7b9ced3256d6be8dfb5f7f05a01bbefe1b9/src/preferences.c#L1323
I'll try to fix this.

**Comment by ZaWertun** [comment]
Try latest commit from master (c92cb984741a2dfb130d440ea00b5b5e496a2025).
To update - run `git pull` inside source dir.

**Comment by Hultan** [comment]
Great job! Now it works perfectly :-)

What is your recommendation now, do I install it or wait for a new version to show up in the manjaro repos? It was not a critical bug so I don't mind waiting.

**Comment by ZaWertun** [comment]
Good. I think manjaro uses parcellite from sourceforge (real one - http://parcellite.sourceforge.net/), mine is just a fork.
There is also github mirror, but it seems to be too old (https://github.com/rickyrockrat/parcellite).

You can tell manjaro maintaner to apply commit c92cb984741a2dfb130d440ea00b5b5e496a2025 as a patch.
